### PR TITLE
Update to zfit supporting Python 3.10, stop supporting Python 3.6

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
I believe there is no problem in this small package depend on a recent version of zfit. With this PR Python 3.7 to 3.10 gets supported, and that probably solves the package incompatibilities discussed in https://github.com/zfit/phasespace/pull/87.

In any case it is time to have an updated release of this package for more modern dependencies.

If this can be merged rapidly to move forward with https://github.com/zfit/phasespace/pull/87? Thanks for your thoughts @jonas-eschle.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
OK, the zfit API has changed between versions. Maybe the requires changes is something you @jonas-eschle can make quickly since in your brain? Else I can try and have a look.

**Comment by eduardo-rodrigues** [comment]
Seems this is what is best before moving to zfit 0.11, which breaks the API. Could this warrant a release, then, to hopefully solve https://github.com/zfit/phasespace/pull/87 while at it?

**Comment by jonas-eschle** [comment]
Indeed, I'll check that, thanks a lot for the PR, this should work with the newest version, but I think something weird upstreams broke

**Comment by eduardo-rodrigues** [comment]
Thanks. Let me know if there is anything else needed here for that dependent MR in `phasespace`. Otherwise I will wait for the approval and merge, to finalise :-). (The pre-commit error is a nuisance at the moment. It can be ignored for now.)

**Comment by eduardo-rodrigues** [comment]
Any news on whether this can go in and we move towards a release, to fix that issue in `phasespace` ;-)?

**Comment by jonas-eschle** [comment]
Looks good, many thanks for this and apologies for the delay! I'll tackle the phasespace issue as well

**Pull request merged**
