### PR TITLE
Add relativistic Breit-Wigner PDF with analytic CDF

### PR DESCRIPTION
**Pull request by simonthor**
## Proposed Changes
This is similar to #2 except:
- [x] More tests
- [x] Analytic CDF instead of numeric
- [x] no merge conflicts
- [x] No squared function

## Tests added

  - Test that the `sample` function works
  - Compare a point on the PDF with an already known value
  - Compare the analytical integral with the numerical integral 

## Checklist

 - [x] change approved
 - [x] implementation finished
 - [x] correct namespace imported
 - [x] tests added
 - [x] CHANGELOG updated

### CODE REVIEW

**Comment by simonthor** [comment]
This PDF should now work. I was a bit unsure about a few things when implementing this though:
- Right now, the input parameters are called `m` and `Gamma` (with a capital G), based on [wikipedia's names](https://en.wikipedia.org/wiki/Relativistic_Breit%E2%80%93Wigner_distribution). Should I change these names to something else?
- Should the PDF be moved to unstable first, instead of being in the model directory?
- Are there some other tests that should be added?
- Right now, I do not have many type hints, as I was not sure which kinds of inputs the functions should accept. Should these type hints be added or can it be left as it is?

**Comment by jonas-eschle** [comment]
> Right now, the input parameters are called `m` and `Gamma` (with a capital G), based on [wikipedia's names](https://en.wikipedia.org/wiki/Relativistic_Breit%E2%80%93Wigner_distribution). Should I change these names to something else?

Let's use the non-capital one (as it's a Python convention for all names)

> Should the PDF be moved to unstable first, instead of being in the model directory?

That's fine, we can go directly to production

> * Are there some other tests that should be added?

This looks fine so far

> * Right now, I do not have many type hints, as I was not sure which kinds of inputs the functions should accept. Should these type hints be added or can it be left as it is?

They can be left aside for the time being, as I am currently anyway reworking them

**Comment by jonas-eschle** [comment]
@all-contributors please add @simonthor

**Comment by jonas-eschle** [comment]
@all-contributors please add @simonthor for code and ideas

**Comment by jonas-eschle** [comment]
@all-contributors please add @simonthor for code and ideas

**Comment by jonas-eschle** [comment]
@all-contributors please add @simonthor for code and ideas

**Comment by jonas-eschle** [comment]
@all-contributors please add @simonthor for code and ideas

**Comment by jonas-eschle** [comment]
Hey looks good! I just made a small change, so make sure to pull first.

One last thing: can you factor out the computation of the PDF? Basically create a pure function called `relativistic_breit_wigner_func` (or something like that) which takes as arguments x, m, gamma?

**Comment by simonthor** [comment]
> One last thing: can you factor out the computation of the PDF? Basically create a pure function called relativistic_breit_wigner_func (or something like that) which takes as arguments x, m, gamma?

Fixed it now! Named it `relbw_pdf_func` since the stand-alone CDF function is called `relbw_cdf_func`. But can of course change the name if your function name is preferred.

**Comment by jonas-eschle** [comment]
Good, many thanks for this! LGTM!

**Pull request merged**
